import { Roboto } from 'next/font/google';
import "./globals.css";
import AuthProvider from '@/libs/AuthProvider';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotoFont = Roboto({
  subsets: ['latin'],
  weight: ["400"]
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${robotoFont.className} antialiased`}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
